const getters = {
  device: state => state.app.device,
  theme: state => state.app.theme,
  color: state => state.app.color,
  visible: state => state.app.visible,
  isMinimized: state => state.app.isMinimized,
  parentData: state => state.app.parentData,
  dataSetTitle: state => state.app.dataSetTitle,
  dlTagTypeOpt: state => state.app.dlTagTypeOpt,
  total: state => state.app.total,
  pagination: state => state.app.pagination,
  avatar: state => state.user.avatar,
  nickname: state => state.user.name,
  roles: state => state.user.roles,
  userInfo: state => state.user.info,
  addRouters: state => state.permission.addRouters,
  multiTab: state => state.app.multiTab,
  lang: state => state.i18n.lang,
  token: (state) => state.user.token,
  user: (state) => state.user.user,
  isAdmin: (state) => state.user.isAdmin,
  permissions: (state) => state.user.permissions,
  userConfig: (state) => state.user.user.userConfig,
  sidebar: (state) => state.app.sidebar,
  GroupLoading: (state) => state.annotator.GroupLoading,
  currentProjectId: state => state.app.currentProjectId,
}

export default getters
