# Use the official Node.js 18 image as a parent image
FROM node:18 as builder


WORKDIR /usr/src/app

#RUN npm install -g npm@9.8.1

RUN npm config set proxy=
RUN npm config set registry https://registry.npm.taobao.org

RUN npm cache clean --force

RUN npm install -g npm

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . ./

#RUN npm build
#
#COPY dist/  /usr/share/nginx/html/ 
ENV NODE_OPTIONS=--openssl-legacy-provider

RUN npm run build
#
## 使用 Nginx 镜像作为最终镜像
FROM nginx:alpine
#
## 将构建好的应用静态文件复制到 Nginx 静态文件目录
COPY --from=builder /usr/src/app/dist/ /usr/share/nginx/html
COPY --from=builder /usr/src/app/run.sh /usr/local/bin/run.sh

RUN chmod 777 /usr/local/bin/run.sh

COPY nginx.conf /etc/nginx/
#
## Nginx 默认监听 80 端口，无需额外配置
#
## 启动 Nginx
#CMD ["nginx", "-g", "daemon off;"]
ENTRYPOINT ["sh", "/usr/local/bin/run.sh"]

# Specify the command to run the application
#CMD ["npm", "run", "serve"]

